# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    tarif_gratuit: 0
    tarif_enfant: 8
    tarif_reduit: 10
    tarif_normal: 16
    tarif_senior: 12

services:
    booking.service:
        class: AppBundle\Services\BookingService
        arguments: ["@doctrine.orm.default_entity_manager", "%tarif_gratuit%", "%tarif_enfant%", "%tarif_reduit%", "%tarif_normal%", "%tarif_senior%"]
    user.service:
        class: AppBundle\Services\UserService
        arguments: ["@doctrine.orm.default_entity_manager"]
    stripe.service:
        class: AppBundle\Services\StripeService
        arguments: ["%stripe_secret_key%"]
